# Git Branch Manager Configuration
# This file replaces .envrc for tracking branches and merge-back strategy

# Worktree definitions - key is the worktree name, value defines the branch and merge strategy
worktrees:
  # Primary worktree - no merge_into (root of merge chain)
  main:
    branch: main
    description: "Main production branch"

  # Development worktree merges into main
  develop:
    branch: develop
    merge_into: main
    description: "Development integration branch"

  # Feature worktree merges into develop
  feature:
    branch: feature/new-feature
    merge_into: develop
    description: "Feature development branch"

  # Release worktree can merge into develop
  release:
    branch: release/v1.0
    merge_into: develop
    description: "Release preparation branch"