# Git Branch Manager (gbm) Configuration File
# This file should be placed in .gbm/config.toml in your repository root

[settings]
# Directory name for worktrees (relative to repository root)
worktree_prefix = "worktrees"

# Automatically fetch remote branches before operations
auto_fetch = true

# Create missing branches if they don't exist locally or remotely
create_missing_branches = false

[state]
# Last synchronization timestamp (automatically managed)
last_sync = "2024-01-01T00:00:00Z"

# Environment variables being tracked (automatically managed)
tracked_vars = []

[icons]
# Status Icons - Used throughout the CLI for various status indicators
success = "✅"      # Successful operations, valid states
warning = "⚠️"       # Out of sync, needs attention
error = "❌"        # Errors, missing items, validation failures
info = "💡"         # Information, tips, suggestions
orphaned = "🗑️"     # Orphaned worktrees to be cleaned up
dry_run = "🔍"      # Dry run mode indicator
missing = "📁"      # Missing worktrees that need to be created
changes = "🔄"      # Branch changes that need synchronization

# Git Status Icons - Used for git repository state indicators
git_clean = "✓"     # Clean working directory, no changes
git_dirty = "~"     # Dirty working directory, uncommitted changes
git_ahead = "↑"     # Local branch ahead of remote
git_behind = "↓"    # Local branch behind remote
git_diverged = "⇕"  # Local and remote have diverged
git_unknown = "?"   # Unknown git status

# Alternative Icon Sets (uncomment to use):

# Minimal ASCII Icons
# success = "[OK]"
# warning = "[!]"
# error = "[X]"
# info = "[i]"
# orphaned = "[DEL]"
# dry_run = "[DRY]"
# missing = "[ADD]"
# changes = "[CHG]"
# git_clean = "+"
# git_dirty = "*"
# git_ahead = "^"
# git_behind = "v"
# git_diverged = "<>"
# git_unknown = "?"

# Nerdfont Icons (requires a Nerdfont)
# success = ""
# warning = ""
# error = ""
# info = ""
# orphaned = ""
# dry_run = ""
# missing = ""
# changes = ""
# git_clean = ""
# git_dirty = ""
# git_ahead = ""
# git_behind = ""
# git_diverged = ""
# git_unknown = ""

# Simple Text Icons
# success = "PASS"
# warning = "WARN"
# error = "FAIL"
# info = "INFO"
# orphaned = "REMOVE"
# dry_run = "PREVIEW"
# missing = "CREATE"
# changes = "UPDATE"
# git_clean = "CLEAN"
# git_dirty = "DIRTY"
# git_ahead = "AHEAD"
# git_behind = "BEHIND"
# git_diverged = "DIVERGED"
# git_unknown = "UNKNOWN"